float f,T,i;
void setup() {
  pinMode(2,OUTPUT);
  Serial.begin(9600);
}
void loop() {
  //d4
  f=293.7;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //d4
  f=293.7;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //d5
  f=587.7;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //a4
  f=440.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=150;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //G4
  f=415.3;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //g4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //f4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //d4
  f=293.7;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //f4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //c4
  f=261.6;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //c4
  f=261.6;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //d5
  f=587.3;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //a4
  f=440.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=150;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //G4
  f=415.3;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //g4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //f4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //d4
  f=293.7;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //f4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //g4
  f=392.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=150;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
   //d5
  f=587.3;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=100;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  //a4
  f=440.0;
  T=1000000/(2*f); 
  Serial.println(T);
  for(i=0;i<=50;i++)
  {
    digitalWrite(2,HIGH);
    delayMicroseconds(T);
    digitalWrite(2,LOW);
    delayMicroseconds(T);
  }
  delay(10000);
}
